### ISSUE TITLE
Commitizen custom command

### ISSUE THREAD

**Issue by jlanzarotta** [ForkIssues/TrackerWin#2383]
Has anyone implemented a custom commitizen command?  On commit, I would like to use commitizen to create the commit message.

**Comment by ValentinGurkov** [comment]
You can run this with a git hook manager such as `husky` and `lefthook` in your project. We use `leftook` to run customized Git hooks. Here is how I run commitizen:
```yaml
prepare-commit-msg:
    commands:
        commitizen:
            interactive: true
            run: pnpm git-cz --hook
            env:
                LEFTHOOK: 0
```

There are other guide online for running this with `husky` and others,
