### ISSUE TITLE
Git Flow - Config file

### ISSUE THREAD

**Issue by Tanddant** [ForkIssues/TrackerWin#2406]
We're using the git flow option in Fork in our team, and really like it - however everyone having to initialize the flow for the same repo creates some headaches (especially because some clients have requirements for naming of the main branch) - is there an option to push a config file to the repo that fork will find and respect?

Something like

`flow.config.fork` placed in the root of the library, and then just a simple naming definition

```YAML
Production: main
Development: develop
Feature: feature/
Release: release/
Hotfix: hotfix/
VersionPrefix: 

```
